version: "3"

services:
  auth:
    build: .
    ports:
      - "8080:8080"
    environment: 
      - "REDIS_HOST=redis"
    volumes:
      - "./.env:/var/app/.env"
  redis:
    image: redis
    ports:
      - "6379:6379"
  